name: "🚀 publish"

on:
    push:
        branch: 
          -master

jobs:
    release:
        name: 🚀 publish
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v4.0.0
            - name: 🟢 node
              uses: actions/setup-node@v3.8.1
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}